site_name: 萝卜真题
copyright: |
    Copyright &copy; 2025 萝卜真题 | 本站资源来源于网络,如有侵权,请联系我们,我们将尽快处理 | 
    <a href="http://beian.miit.gov.cn" target="_blank" rel="noopener">皖ICP备2025097063号-1</a>
theme:
  name: material
  language: zh
  custom_dir: overrides
  font: false
  favicon: assets/favicon.png

  icon:
    logo: fontawesome/solid/carrot

  palette:
    primary: teal
    accent: orange

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs

# 启用 hooks 文件
hooks:
  - hooks/md.py

extra:
  generator: false  # 去除底部 mkdocs 推广链接

# 排除不需要发布的目录和文件
exclude_docs: |
  drafts/    # 草稿
  internal/  # 内部文档

watch:
  - hooks/md.py
  - overrides



